spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dvbank
    username: root
    password: 123456a@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    rest:
      detection-strategy: annotated

logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: debug